### ISSUE TITLE
Update team and supporter sessions 

### ISSUE THREAD

**Issue by hpdang** [OpnTec/open-spectrometer-hardware#4]
- Remove Miya and Jack into the team 
- Remove logo of DevEco & freeCodeCamp 
- Add new team members

Lian Xiao Bei - Event Coordinator - 491859500@qq.com - Weichat ID: lenkalian
Waiting for photo

Xing Hai Jiao - Press & Media Coordinator - 791153692@qq.com - Weichat ID: elizabeth_e
![xinghaijiao](https://user-images.githubusercontent.com/1658742/39281311-1ac5dcdc-492e-11e8-9298-d306b39fc237.jpeg)

Wen QiXiang - Event Manager - wen@bootingman.org - Weichat ID: bootingman
Waiting for photo

Mie Lam - Office Admin - mielam@fossasia.org - Weichat ID: mielam
https://github.com/fossasia/fossasia.org/blob/gh-pages/img/MieLam.jpg

Eden Dang - Program Manager - eden@fossasia.org - Weichat ID: edenyay
https://github.com/fossasia/2018.fossasia.org/blob/master/img/EdenDang.jpg

**Comment by sarnava1** [comment]
Can I work on this issue?

**Comment by sarnava1** [comment]
@mariobehling @hpdang can I help with this?
